addSbtPlugin("org.scalameta"             % "sbt-scalafmt"         % "2.4.5")
addSbtPlugin("net.virtual-void"          % "sbt-dependency-graph" % "0.9.2")
//another plugin is getting sbt-pgp 1.1.0
//addSbtPlugin("com.jsuereth"              % "sbt-pgp"              % "2.0.1")
addSbtPlugin("org.xerial.sbt"            % "sbt-sonatype"         % "3.9.10")
addSbtPlugin("com.eed3si9n"              % "sbt-buildinfo"        % "0.10.0")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"        % "1.9.2")
addSbtPlugin("ch.epfl.scala"             % "sbt-release-early"    % "2.1.1")
addSbtPlugin("com.47deg"                 % "sbt-microsites"       % "1.3.4")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"         % "0.9.33")
addSbtPlugin("pl.project13.scala"        % "sbt-jmh"              % "0.4.3")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"         % "0.1.20")
